
sudo: false
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $CI_TOKEN
  keep-history: true
  allow-empty-commit: false
  target-branch: gh-pages
  on:
    branch: master

language: node_js

node_js:
  - 8

before_script:
- npm install yarn -g
- yarn | npm install

script:
- yarn run build